// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // El CLI de Prisma (migraciones, introspección, studio) usa la conexión
    // DIRECTA de Supabase (puerto 5432), no el pooler. El runtime de la app usa
    // DATABASE_URL (pooler) a través del adapter en src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
